names_file: /home/dietpi/workbench/Sombrero_No_Tan_Sabio/code/python/nombres_y_mesas.json
log_file: /home/dietpi/Desktop/log_sombrero_seleccionador.txt
arduino:
  port: COM4
  baud_rate: 9600
pyttsx3:
  rate: 180
  volume: 0.9